num_features: [
  "l_feat_4",
  "l_feat_8",
  "l_feat_10",
  "l_feat_13",
  "l_feat_16",
  "l_feat_18",
  "l_feat_19",
  "l_feat_25",
  "feat_a_5",
  "feat_a_14",
  "feat_e_1",
  "feat_e_2",
  "feat_e_3",
  "feat_e_5",
  "feat_e_6",
  "feat_e_7",
  "feat_e_8",
  "feat_e_9",
  "feat_e_10",
  "feat_d_4",
  "feat_c_2",
  "feat_b_1",
  "feat_b_2",
  "feat_b_3",
  "feat_b_4",
  "feat_b_5",
  "feat_b_6",
  "history_a_1",
  "history_a_2",
  "history_a_3",
  "history_a_4",
  "history_a_5",
  "history_a_6",
  "history_a_7",
  "history_b_1",
  "history_b_2",
  "history_b_3",
  "history_b_4",
  "history_b_5",
  "history_b_6",
  "history_b_7",
  "history_b_8",
  "history_b_9",
  "history_b_10",
  "history_b_11",
  "history_b_12",
  "history_b_13",
  "history_b_14",
  "history_b_15",
  "history_b_16",
  "history_b_17",
  "history_b_18",
  "history_b_19",
  "history_b_20",
  "history_b_21",
  "history_b_22",
  # "history_b_23",
  "history_b_24",
  "history_b_25",
  "history_b_26",
  "history_b_27",
  "history_b_28",
  "history_b_29",
  "history_b_30",
  "feat_b_1_div_feat_b_3",
  "feat_b_1_div_feat_b_6",
  "feat_b_3_div_feat_b_6",
  "feat_e_2_div_feat_e_7",
  "feat_e_2_div_feat_e_10",
  "feat_e_7_div_feat_e_10",
  "history_a1_a2_ratio",
  "history_a3_a4_ratio",
  "history_b_last3_sum",
  "history_b_last3_mean",
  "history_b_last3_max",
  "history_b_last_ratio",
  "seq_len",
  "seq_unique",
  "diversity_ratio",
  "entropy",
]

# TCN encoder features (32-dimensional embeddings from history_b_1~30)
tcn_features: [
  "tcn_emb_1",
  "tcn_emb_2",
  "tcn_emb_3",
  "tcn_emb_4",
  "tcn_emb_5",
  "tcn_emb_6",
  "tcn_emb_7",
  "tcn_emb_8",
  "tcn_emb_9",
  "tcn_emb_10",
  "tcn_emb_11",
  "tcn_emb_12",
  "tcn_emb_13",
  "tcn_emb_14",
  "tcn_emb_15",
  "tcn_emb_16",
  "tcn_emb_17",
  "tcn_emb_18",
  "tcn_emb_19",
  "tcn_emb_20",
  "tcn_emb_21",
  "tcn_emb_22",
  "tcn_emb_23",
  "tcn_emb_24",
  "tcn_emb_25",
  "tcn_emb_26",
  "tcn_emb_27",
  "tcn_emb_28",
  "tcn_emb_29",
  "tcn_emb_30",
  "tcn_emb_31",
  "tcn_emb_32",
]

# Feature usage flags
use_tcn_features: true
use_history_b_features: true  # Whether to use original history_b_1~30 features

cat_features: [
  "gender",
  "age_group",
  "inventory_id",
  "hour",
  "feat_a_1",
  "feat_a_2",
  "feat_a_3",
  "feat_a_4",
  "feat_a_6",
  "feat_a_7",
  "feat_a_8",
  "feat_a_9",
  "feat_a_10",
  "feat_a_11",
  "feat_a_12",
  "feat_a_17",
  "feat_a_16",
  "feat_a_18",
  "l_feat_1",
  "l_feat_2",
  "l_feat_3",
  "l_feat_21",
  "l_feat_22",
  "l_feat_24",
  "l_feat_26",
  "l_feat_27",
  "feat_d_1",
  "feat_d_2",
  "feat_d_3",
  "feat_d_5",
  "feat_d_6",
  "feat_e_4",
]

count_features: [
  "gender_count",
  "age_group_count",
  "inventory_id_count",
  "feat_a_1_count",
  "feat_a_2_count",
  "feat_a_3_count",
  "feat_a_4_count",
  "feat_a_6_count",
  "feat_a_7_count",
  "feat_a_8_count",
  "feat_a_9_count",
  "feat_a_10_count",
  "feat_a_11_count",
  "feat_a_12_count",
  "feat_a_17_count",
  "feat_a_16_count",
  "feat_a_18_count",
  "l_feat_1_count",
  "l_feat_2_count",
  "l_feat_3_count",
  "l_feat_21_count",
  "l_feat_22_count",
  "l_feat_24_count",
  "l_feat_26_count",
  "l_feat_27_count",
  "feat_d_1_count",
  "feat_d_2_count",
  "feat_d_3_count",
  "feat_d_5_count",
  "feat_d_6_count",
  "feat_e_4_count",
]