_target_: models.tree.LightGBMTrainer

params:
  boosting_type: dart
  data_sample_strategy: bagging
  objective: binary
  metric: competition_score
  learning_rate: 0.05
  bagging_seed: 42
  num_leaves: 128
  max_depth: -1
  min_child_weight: 0.03
  bagging_fraction: 0.8
  feature_fraction: 0.8
  lambda_l1: 0.04
  lambda_l2: 0.06
  num_threads: -1
  scale_pos_weight: 51.42546491069111

model_path: res/models/
results: 10fold-lightgbm-denoise-category-dart-seed42
early_stopping_rounds: 100
num_boost_round: 2000
verbose_eval: 100
seed: 42