name: tree4-dcn2-mha-concatmod-sigmoid-ensemble

preds:
- 10fold-lightgbm-denoise-category-dart-seed42
- 10fold-lightgbm-denoise-category-dart-seed919
- 10fold-lightgbm-denoise-category-dart-seed1119
- 10fold-xgboost-denoise-count-gbtree-seed42
- 5fold-dcn-mha-concat
- 5fold-dcn_v2-mha-concat

weights: null
method: sigmoid
